// Minimal MCP face over the vendored communicate CLI. No fabric logic here:
// every tool is one spawn of the CLI. APPEND ONLY — order is the tools/list contract.
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { communicateCli, packageVersion } from "./paths.mjs";

const exec = promisify(execFile);
const run = async (args, timeoutMs = 120000) => (await exec(communicateCli, args, { encoding: "utf8", timeout: timeoutMs, maxBuffer: 8 * 1024 * 1024 })).stdout;
const text = (s) => ({ content: [{ type: "text", text: s || "(no output)" }] });
const fail = (e) => ({ content: [{ type: "text", text: String(e.stdout || e.stderr || e.message || e) }], isError: true });

// Handshake guidance is also available to clients that expose MCP instructions.
// Client activation is verified separately; a handshake is not a system prompt.
const INSTRUCTIONS = `COM8 lets agents create workers, exchange messages and return actual results. Perform the tool calls for the user's request; do not hand them a list of commands. Keep address spaces distinct: com8_* tools address persistent identities and terminal seats; bus_* tools address exact registrations on a selected hub; agents_list/route/send/ask and codex_* tools use native sessions. A matching name in another space is not a substitute.
When asked to register yourself on the bus, discover bus agents or open its dashboard, inspect bus_status first; it never starts services. Use the configured hub unless the user selected another. COM8's hosted hub at https://bus.nonlocally.org is an option alongside local and self-hosted operation. An explicit request for that hub requires enrollment there: inspect bus_status with its hub URL and use that same hub for registration/discovery/sends. If unconfigured, redeem the user-supplied personal invitation or shared event code through CLI connect --invite-stdin, or request one if absent; then register this exact session on the granted bus. Event codes intentionally support sharing with participants; keep the returned device credential private. Never silently substitute a local broker. Installation, provider login, browser sign-in and Tailscale reachability do not enroll a device. For unspecified scope without a configured hub, follow the user's stated local/shared intent or clarify it. Existing CLI connect/use commands handle enrollment and selection; see communicate-bus.
Register the exact existing Claude socket or CODEX_THREAD_ID. If MCP lacks that context, run the equivalent CLI in this session's shell; never guess the newest session or create a replacement. General permits an unpublished exact local sender on an enrolled device to initiate to a published recipient. Private buses require explicit membership; joining one does not also join general. Preserve the originating hub, recipient ID and reply command; bus_reply keeps the original participants and fixed 24-hour window. Names, email addresses and device labels do not establish account ownership. Keep invitations, credentials and dashboard fragment tokens private.
For a new worker, inspect com8_status and com8_agents; start the local daemon when needed, then com8_spawn in the intended project. When the user selects GLM or another configured model, inspect com8_model_list and pass the exact connection as model_connection; this powers the coding client itself and does not change its ordinary subscription defaults. com8_model_doctor checks catalog access, not successful inference. Never fall back to another model or ask for API keys in messages; private connection setup uses the CLI's hidden prompt, key file or stdin. Its seat driver creates the configured tmux session (default server com8, session com8-seats). Verify Claude adoption and a live, unambiguous native route. A spawned Codex durable name is not automatically a queue binding: establish its exact thread before using the native/bus queue. Missing tools, login or routing are blockers, not successful execution. Use com8_ask with a claimed task sender and the supplied reply token for a verified durable recipient. Return its actual answer; follow com8-core for details.
A stored message, queue receipt and model reply are different results. Queueing does not prove consumption or desktop wake. Report held, refused, unavailable or timed-out delivery without blind retries. A process restart does not prove restored conversation state; legacy natural-reply fallback is not explicit correlation. Terminal input is separate permission to execute commands; remote seat control and keyboard relay require their existing grants. Claim release, process termination and deletion of saved data remain distinct. Terminal/mesh profiles are optional; the bus dashboard, graph and human inbox remain available.`;
const identityName = z.string().regex(/^[a-z0-9][a-z0-9._-]*$/);
const seconds = z.number().min(0.1).max(600);
// The CLI prints the dashboard link with this device's bus credential in its
// fragment. That link belongs in the person's own browser, never in a transcript.
const dashboardResult = (out, a) => {
  let origin;
  try { origin = new URL(out.trim()).origin; } catch { return "The bus dashboard link could not be read; run com8 bus dashboard --open in a terminal on this computer."; }
  return a.open
    ? `Asked this computer's default browser to open the bus dashboard at ${origin}. Its link carries this device's bus credential, so it is not shown here. If nothing opened, for example on a remote or headless machine, run com8 bus dashboard in a terminal there.`
    : `Bus dashboard: ${origin}. Its link carries this device's bus credential, so it is not returned here. Call bus_dashboard with open: true to open it in this computer's browser, or run com8 bus dashboard --open in a terminal on this computer.`;
};

const TOOLS = [
  { name: "agents_list", desc: "Legacy socket routing table (separate from explicit bus membership): local Claude sessions, bridged remotes, and Codex peers with status, working dir, and DESCRIPTION — each session's own chat title. Match intent against descriptions, then address by exact name.", schema: { json: z.boolean().optional().describe("machine-readable rows incl. sockets") }, argv: (a) => a.json ? ["agents", "--json"] : ["agents"] },
  { name: "whereis", desc: "Resolve an agent name to type/via/socket.", schema: { name: z.string() }, argv: (a) => ["whereis", a.name] },
  { name: "route", desc: "Send a message to any agent by name (Claude or Codex, local or bridged). The reply returns to the caller's messaging socket when one exists.", schema: { name: z.string(), message: z.string() }, argv: (a) => ["route", a.name, a.message] },
  { name: "send", desc: "Raw-inject one message into a peer socket or named peer, with optional from-name attribution.", schema: { target: z.string(), message: z.string(), as: z.string().optional() }, argv: (a) => a.as ? ["send", a.target, "--as", a.as, "--", a.message] : ["send", a.target, "--", a.message] },
  { name: "codex_queue", desc: "Enqueue a turn into an EXISTING Codex session by native name/UUID (async; the reply stays in that session). Codex CLI >= 0.151.", schema: { device: z.string(), session: z.string(), message: z.string() }, argv: (a) => ["codex", "queue", a.device, a.session, "--", a.message] },
  { name: "codex_ask", desc: "Ask a headless Codex agent synchronously (codex exec with remembered thread continuity; read-only sandbox unless auto).", schema: { device: z.string(), message: z.string(), dir: z.string().optional(), thread: z.string().optional(), fresh: z.boolean().optional(), auto: z.boolean().optional() }, argv: (a) => ["codex", "ask", a.device, ...(a.dir ? ["--dir", a.dir] : []), ...(a.thread ? ["--thread", a.thread] : []), ...(a.fresh ? ["--new"] : []), ...(a.auto ? ["--auto"] : []), "--", a.message] },
  { name: "status", desc: "Active bridges, codex peers, and wakes started by communicate on this machine.", schema: {}, argv: () => ["status"] },
  { name: "ask", desc: "Ask any agent by name and WAIT for the reply. Works on Claude sessions/peers and on local Codex sessions (by native thread name). The delivered question carries an in-band [reply-to ...] block teaching the receiver exactly how to answer, so nothing needs to be installed on their side.", schema: { name: z.string(), message: z.string(), timeout: z.number().optional().describe("seconds to wait (default 90)") }, argv: (a) => ["ask", a.name, "--timeout", String(a.timeout ?? 90), "--", a.message], timeoutMs: (a) => ((a.timeout ?? 90) + 30) * 1000 },
  { name: "card_set", desc: "Set a legacy socket-roster card (Claude sidecar identity). Cards beat chat titles in that roster and survive resumes. For explicit bus registrations, use bus_register with description instead.", schema: { name: z.string().describe("agent name, or 'self'"), what: z.string().optional(), ask_me_for: z.string().optional() }, argv: (a) => ["card", "set", a.name, ...(a.what ? ["--what", a.what] : []), ...(a.ask_me_for ? ["--ask-me-for", a.ask_me_for] : [])] },
  { name: "bus_register", desc: "Inspect bus_status first, then publish this existing agent on general for discovery and incoming requests, or explicitly join a private named bus. Defaults to self/general; a named bus joins only that bus. Resolves the current Claude socket or CODEX_THREAD_ID, never creates a replacement agent. If identity is unavailable through MCP, run the equivalent CLI inside the session shell.", schema: { hub: z.string().optional().describe("connected broker origin, or local; selects this operation only"), target: z.string().optional().describe("self (default), or exact local agent name"), bus: z.string().optional(), name: z.string().optional().describe("bus display alias"), session: z.string().optional().describe("verified existing session ID; never guess"), kind: z.enum(["codex", "claude"]).optional(), description: z.string().optional() }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "register", a.target ?? "self", "--bus", a.bus ?? "general", ...(a.name ? ["--name", a.name] : []), ...(a.session ? ["--session", a.session] : []), ...(a.kind ? ["--kind", a.kind] : []), ...(a.description ? ["--description", a.description] : [])] },
  { name: "bus_list", desc: "Inspect bus_status first, then list buses visible to this device on the selected broker. General is local to that broker, not an internet-wide directory.", schema: { hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "list", "--json"] },
  { name: "bus_agents", desc: "Inspect bus_status first, then list registered agents and their membership/status on the selected bus broker. Codex queueable means an exact existing thread can receive queued turns; it does not prove an active agent.", schema: { bus: z.string().optional(), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "agents", ...(a.bus ? ["--bus", a.bus] : []), "--json"] },
  { name: "bus_leave", desc: "Remove this session's membership in one bus.", schema: { target: z.string().optional().describe("self (default), or registered agent ID"), bus: z.string().optional(), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "leave", a.target ?? "self", "--bus", a.bus ?? "general"] },
  { name: "bus_send", desc: "Initiate a conversation with a published recipient. General permits any exact local agent on an enrolled device without publishing the sender; private buses require both agents to join. Use bus_reply for answers. Returns a receipt, not an agent answer.", schema: { target: z.string(), message: z.string(), bus: z.string().optional(), from: z.string().optional().describe("self (default), or sender registration ID owned by this device"), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "send", a.target, "--bus", a.bus ?? "general", "--from", a.from ?? "self", "--", a.message] },
  { name: "bus_receipt", desc: "Inspect delivery status for a bus message receipt. Distinguishes gateway acceptance from endpoint delivery or Codex queueing; does not assert an answer.", schema: { id: z.string(), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "receipt", a.id] },
  { name: "bus_status", desc: "Inspect this device's selected broker and worker without starting services. configured:false means this selection has no saved connection; it does not imply that another configured hub is absent.", schema: { hub: z.string().optional().describe("broker origin to inspect, or local; an unconnected origin reports configured:false without starting services") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "status", "--json", "--no-start"] },
  { name: "bus_dashboard", desc: "Inspect bus_status first, then open the selected bus interface in this computer's browser (open: true) or report its address. Its authenticated link carries this device's bus credential and is never returned.", schema: { hub: z.string().optional().describe("connected broker origin, or local; selects this operation only"), open: z.boolean().optional().describe("open the authenticated dashboard in this computer's default browser") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "dashboard", ...(a.open ? ["--open"] : [])], result: dashboardResult },
  { name: "bus_create", desc: "Inspect bus_status first, then create a named bus using broker-administrator credentials, including the local owner. Ordinary enrolled device tokens cannot create buses. Admitted hosted users create their own project buses in the signed-in dashboard, then enroll devices and register agents there; see communicate-bus.", schema: { name: z.string(), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "create", a.name] },
  { name: "bus_device", desc: "Refresh this installation's device metadata or display name on the selected broker. Stable device identity and administrator-assigned account ownership do not change. Only this machine's hostname, platform, and optional Tailscale Self names are collected.", schema: { name: z.string().optional().describe("new display label for this device"), hub: z.string().optional().describe("connected broker origin, or local; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "device", ...(a.name ? ["--name", a.name] : [])] },
  { name: "bus_reply", desc: "Reply to a message received by this exact agent, within its original participants and bus. The conversation expires 24 hours after initiation; replies do not extend it. This permits replies to unpublished general senders without publishing them.", schema: { id: z.string().describe("received message ID"), message: z.string(), from: z.string().optional().describe("self (default), or original recipient registration ID owned by this device"), hub: z.string().optional().describe("originating connected broker; selects this operation only") }, argv: (a) => ["bus", ...(a.hub ? ["--hub", a.hub] : []), "reply", a.id, "--from", a.from ?? "self", "--", a.message] },

  // Durable COM8 tools append to the original native/bus list. Every operation
  // delegates to the existing CLI and daemon; no second message store or resolver.
  { name: "com8_status", desc: "Inspect the durable daemon, identities and measured execution state. Does not start it.", schema: {}, argv: () => ["com8", "status", "--json"] },
  { name: "com8_start", desc: "Start the existing local durable COM8 daemon when requested. Does not enroll a remote device or spawn an agent.", schema: {}, argv: () => ["com8", "start"] },
  { name: "com8_agents", desc: "List durable identities, messages and current execution bindings; separate from native sessions and bus registrations.", schema: {}, argv: () => ["com8", "agents", "--json"] },
  { name: "com8_claim", desc: "Create a persistent identity that can receive messages without starting an agent. Existing claims are retained.", schema: { name: identityName, cwd: z.string().optional() }, argv: (a) => ["com8", "claim", a.name, ...(a.cwd ? ["--cwd", a.cwd] : [])] },
  { name: "com8_release", desc: "Release a durable identity's active claim. This is not execution termination or deletion of its saved messages.", schema: { name: identityName }, argv: (a) => ["com8", "release", a.name] },
  { name: "com8_send", desc: "Store and route a message to a durable identity (optionally name@device). A successful route is not an agent answer.", schema: { target: z.string(), message: z.string(), from: identityName }, argv: (a) => ["com8", "send", a.target, "--from", a.from, "--", a.message] },
  { name: "com8_ask", desc: "Send to a durable identity and wait for a reply. Prefer the supplied explicit token; the legacy natural-reply fallback remains best-effort.", schema: { target: z.string(), message: z.string(), from: identityName, timeout: seconds.optional() }, argv: (a) => ["com8", "ask", a.target, "--from", a.from, "--timeout", String(a.timeout ?? 90), "--json", "--", a.message], timeoutMs: (a) => ((a.timeout ?? 90) + 30) * 1000 },
  { name: "com8_reply", desc: "Answer using the exact durable request's reply token and your claimed identity.", schema: { token: z.string(), message: z.string(), from: identityName }, argv: (a) => ["com8", "reply", a.token, "--from", a.from, "--", a.message] },
  { name: "com8_inbox", desc: "Read saved messages for a local persistent identity as JSON lines. Reading does not claim execution or completion.", schema: { name: identityName }, argv: (a) => ["com8", "inbox", a.name] },
  { name: "com8_wait", desc: "Wait for new messages at a durable local identity. This does not start a sleeping model process.", schema: { name: identityName, timeout: seconds.optional() }, argv: (a) => ["com8", "wait", a.name, "--timeout", String(a.timeout ?? 60), "--json"], timeoutMs: (a) => ((a.timeout ?? 60) + 30) * 1000 },
  { name: "com8_spawn", desc: "Create a durable identity and start Claude Code or Codex in a tmux seat. An explicit model_connection selects a configured model such as GLM to power the client; otherwise uses its existing provider authentication.", schema: { name: identityName, cli: z.enum(["claude", "codex"]), cwd: z.string().optional(), model_connection: identityName.optional() }, argv: (a) => ["com8", "spawn", a.name, "--cli", a.cli, ...(a.cwd ? ["--cwd", a.cwd] : []), ...(a.model_connection ? ["--model-connection", a.model_connection] : []), "--json"] },
  { name: "com8_restart", desc: "Restart an existing supervised identity using its recorded command/cwd. Process restart is not proof of restored conversation state.", schema: { name: identityName }, argv: (a) => ["com8", "restart", a.name] },
  { name: "com8_seats", desc: "List terminal seats and the observed socket/PID of the daemon's configured tmux server. Pane IDs are local to that server's lifetime.", schema: {}, argv: () => ["com8", "seat", "ls", "--json"] },
  { name: "com8_seat_spawn", desc: "Explicitly run a command in a new terminal seat and return its tmux server socket/PID. Remote creation needs an existing link with seat permission. An ordinary seat is not sandboxed.", schema: { command: z.string(), cwd: z.string().optional(), device: z.string().optional() }, argv: (a) => ["com8", "seat", "spawn", "--json", ...(a.cwd ? ["--cwd", a.cwd] : []), ...(a.device ? ["--device", a.device] : []), "--", a.command] },
  { name: "com8_seat_send", desc: "Explicitly submit terminal input to a seat. This can execute shell commands; it is not agent messaging.", schema: { seat: z.string(), input: z.string() }, argv: (a) => ["com8", "seat", "send", a.seat, a.input] },
  { name: "com8_seat_read", desc: "Read a terminal screen and observed state; screen text is not a correlated agent answer.", schema: { seat: z.string(), lines: z.number().int().min(1).max(2000).optional() }, argv: (a) => ["com8", "seat", "read", a.seat, "--lines", String(a.lines ?? 40)] },
  { name: "com8_seat_state", desc: "Observe a seat's terminal state. Unknown means the driver could not establish its state, not that it died.", schema: { seat: z.string() }, argv: (a) => ["com8", "seat", "state", a.seat] },
  { name: "com8_seat_bind", desc: "Bind a seat to a claimed identity. Keyboard relay is a separate explicit opt-in, not implied by binding.", schema: { seat: z.string(), name: identityName, relay: z.boolean().optional() }, argv: (a) => ["com8", "seat", "bind", a.seat, a.name, ...(a.relay ? ["--relay"] : [])] },
  { name: "com8_seat_interrupt", desc: "Send Escape to the selected seat using the existing driver. The identity and saved messages remain.", schema: { seat: z.string() }, argv: (a) => ["com8", "seat", "interrupt", a.seat] },
  { name: "com8_seat_kill", desc: "Terminate the selected terminal pane when explicitly requested. This does not delete its durable identity or saved state.", schema: { seat: z.string() }, argv: (a) => ["com8", "seat", "kill", a.seat] },
  { name: "com8_model_list", desc: "List locally configured model connections without credentials or network calls. Use the exact connection name with com8_spawn model_connection when the user selects a model such as GLM.", schema: {}, argv: () => ["com8", "model", "list", "--json"] },
  { name: "com8_model_doctor", desc: "Check a configured model's authenticated catalog access and model ID. This sends a discovery request to its configured endpoint; it does not perform inference or prove a coding client works.", schema: { name: identityName }, argv: (a) => ["com8", "model", "doctor", a.name, "--json"] },

];

export async function runServe() {
  const server = new McpServer({ name: "communicate", version: packageVersion }, { instructions: INSTRUCTIONS });
  for (const t of TOOLS) {
    server.registerTool(t.name, { description: t.desc, inputSchema: t.schema }, async (args) => {
      const a = args ?? {};
      try {
        const out = await run(t.argv(a), t.timeoutMs ? t.timeoutMs(a) : undefined);
        return text(t.result ? t.result(out, a) : out);
      } catch (e) { return fail(e); }
    });
  }
  await server.connect(new StdioServerTransport());
}
